import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import { SessionProvider } from "next-auth/react";
import { Underdog } from "next/font/google";
import { Pacifico } from "next/font/google";
import { Lato } from "next/font/google";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const lato = Lato({
  subsets: ["latin"],
  weight: "400",
  variable: "--lato",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--pacifico",
});

const underDog = Underdog({
  subsets: ["latin"],
  weight: "400",
  variable: "--underdog",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <SessionWrapper>
        <SessionProvider>
          <body className="hide-scrollbar">
            <div className="flex hide-scrollbar flex-col min-h-screen ">
              {children}
              <ToastContainer position="top-right" autoClose={3000} />
            </div>

            <Footer />
          </body>
        </SessionProvider>
      </SessionWrapper>
    </html>
  );
}
